import type { Restaurant, RegionGap, RegionGapDetail, RestaurantFilter } from './types';
import regionGapJson from '@/public/data/region-gap.json';
import { applyRestaurantFilter } from './filter';

export const RESTAURANTS: Restaurant[] = [
  {
    id: 'r-yongsan-samgyetang',
    name: { en: 'Yongsan Samgyetang House', ko: '용산 삼계탕집', ar: 'بيت سامغيتانغ يونغسان', hi: 'योंगसान समगयेतांग हाउस' },
    area: { en: 'Yongsan-gu, Seoul', ko: '서울 용산구', ar: 'يونغسان، سيول', hi: 'योंगसान-गु, सियोल' },
    sigunguCode: '11030',
    coords: [126.9779, 37.5384],
    cuisine: 'korean-chicken',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: false },
    confidence: 'phone',
    matchedTokens: ['삼계탕', '닭'],
    repMenu: ['삼계탕', '전복삼계탕'],
    phoneVerifiedOn: '2026-03-14',
  },
  {
    id: 'r-itaewon-kebab',
    name: { en: 'Itaewon Halal Kebab', ko: '이태원 할랄 케밥', ar: 'كباب حلال إيتايوون', hi: 'इतायवोन हलाल कबाब' },
    area: { en: 'Yongsan-gu, Seoul', ko: '서울 용산구', ar: 'يونغسان، سيول', hi: 'योंगसान-गु, सियोल' },
    sigunguCode: '11030',
    coords: [126.9946, 37.5345],
    cuisine: 'halal',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: true, vegetarianFriendly: true },
    confidence: 'phone',
    matchedTokens: ['케밥', 'HALAL', '할랄'],
    repMenu: ['양고기 케밥', '치킨 케밥', '팔라펠'],
    phoneVerifiedOn: '2026-05-02',
  },
  {
    id: 'r-itaewon-turkish',
    name: { en: 'Anatolia Turkish Kitchen', ko: '아나톨리아 터키 키친', ar: 'مطبخ الأناضول التركي', hi: 'अनातोलिया तुर्की किचन' },
    area: { en: 'Yongsan-gu, Seoul', ko: '서울 용산구' },
    sigunguCode: '11030',
    coords: [126.9925, 37.5341],
    cuisine: 'middle-eastern',
    attributes: { containsPork: false, servesAlcohol: 'unknown', containsBeef: true, vegetarianFriendly: true },
    confidence: 'menu',
    matchedTokens: ['케밥', '터키'],
    repMenu: ['이스켄데르', '렌틸 수프'],
  },
  {
    id: 'r-yongsan-hanwoo',
    name: { en: 'Hannam Hanwoo Table', ko: '한남 한우식탁' },
    area: { en: 'Yongsan-gu, Seoul', ko: '서울 용산구' },
    sigunguCode: '11030',
    coords: [126.9987, 37.5346],
    cuisine: 'korean-beef',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: true, vegetarianFriendly: false },
    confidence: 'menu',
    matchedTokens: ['한우', '등심'],
    repMenu: ['한우 등심', '육회'],
  },
  {
    id: 'r-jongno-samgyetang',
    name: { en: 'Tosokchon Style Samgyetang', ko: '토속촌식 삼계탕', ar: 'سامغيتانغ على طريقة توسوكشون', hi: 'तोसोकचोन शैली समगयेतांग' },
    area: { en: 'Jongno-gu, Seoul', ko: '서울 종로구', ar: 'جونغنو، سيول', hi: 'जोंगनो-गु, सियोल' },
    sigunguCode: '11010',
    coords: [126.9704, 37.5787],
    cuisine: 'korean-chicken',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: false },
    confidence: 'phone',
    matchedTokens: ['삼계탕'],
    repMenu: ['삼계탕', '오골계탕'],
    phoneVerifiedOn: '2026-01-22',
  },
  {
    id: 'r-jongno-temple',
    name: { en: 'Insadong Temple Cuisine', ko: '인사동 사찰음식', ar: 'مطبخ المعبد إنسا-دونغ', hi: 'इनसा-डोंग मंदिर भोजन' },
    area: { en: 'Jongno-gu, Seoul', ko: '서울 종로구', ar: 'جونغنو، سيول', hi: 'जोंगनो-गु, सियोल' },
    sigunguCode: '11010',
    coords: [126.9852, 37.5744],
    cuisine: 'temple',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: true },
    confidence: 'menu',
    matchedTokens: ['사찰음식', '채식'],
    repMenu: ['사찰정식', '연잎밥', '버섯전골'],
  },
  {
    id: 'r-jongno-hanwoo',
    name: { en: 'Gwanghwamun Hanwoo Jip', ko: '광화문 한우집' },
    area: { en: 'Jongno-gu, Seoul', ko: '서울 종로구' },
    sigunguCode: '11010',
    coords: [126.9769, 37.5721],
    cuisine: 'korean-beef',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: true, vegetarianFriendly: false },
    confidence: 'name',
    matchedTokens: ['한우'],
    repMenu: ['한우 갈비', '갈비탕'],
  },
  {
    id: 'r-jongno-bibimbap',
    name: { en: 'Jongno Namul Bibimbap', ko: '종로 나물 비빔밥' },
    area: { en: 'Jongno-gu, Seoul', ko: '서울 종로구' },
    sigunguCode: '11010',
    coords: [126.9887, 37.5709],
    cuisine: 'korean',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: true },
    confidence: 'menu',
    matchedTokens: ['비빔밥', '나물'],
    repMenu: ['산채비빔밥', '된장찌개'],
  },
  {
    id: 'r-mapo-hoetjip',
    name: { en: 'Mapo Mullhoe Hoetjip', ko: '마포 물회 횟집' },
    area: { en: 'Mapo-gu, Seoul', ko: '서울 마포구', ar: 'مابو، سيول', hi: 'मापो-गु, सियोल' },
    sigunguCode: '11140',
    coords: [126.9084, 37.5559],
    cuisine: 'seafood',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: false, vegetarianFriendly: false },
    confidence: 'phone',
    matchedTokens: ['횟집', '물회'],
    repMenu: ['물회', '광어회', '매운탕'],
    phoneVerifiedOn: '2026-04-09',
  },
  {
    id: 'r-mapo-halal-curry',
    name: { en: 'Hongdae Halal Curry Bar', ko: '홍대 할랄 커리 바', ar: 'بار كاري حلال هونغدايه', hi: 'होंगदे हलाल करी बार' },
    area: { en: 'Mapo-gu, Seoul', ko: '서울 마포구', ar: 'مابو، سيول', hi: 'मापो-गु, सियोल' },
    sigunguCode: '11140',
    coords: [126.9235, 37.5563],
    cuisine: 'indian',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: true },
    confidence: 'phone',
    matchedTokens: ['HALAL', '커리', '할랄'],
    repMenu: ['버터 치킨', '달 마크니', '가르릭 난'],
    phoneVerifiedOn: '2026-02-18',
  },
  {
    id: 'r-mapo-temple',
    name: { en: 'Seogyo Sachal Table', ko: '서교동 사찰상' },
    area: { en: 'Mapo-gu, Seoul', ko: '서울 마포구' },
    sigunguCode: '11140',
    coords: [126.9198, 37.5521],
    cuisine: 'temple',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: true },
    confidence: 'name',
    matchedTokens: ['사찰음식'],
    repMenu: ['사찰비빔밥', '두부전골'],
  },
  {
    id: 'r-mapo-dak',
    name: { en: 'Mangwon Baeksuk House', ko: '망원 백숙집' },
    area: { en: 'Mapo-gu, Seoul', ko: '서울 마포구' },
    sigunguCode: '11140',
    coords: [126.9013, 37.5556],
    cuisine: 'korean-chicken',
    attributes: { containsPork: false, servesAlcohol: 'unknown', containsBeef: false, vegetarianFriendly: false },
    confidence: 'name',
    matchedTokens: ['백숙', '닭'],
    repMenu: ['닭백숙', '녹두삼계탕'],
  },
  {
    id: 'r-busan-jung-hoetjip',
    name: { en: 'Jagalchi Fresh Hoetjip', ko: '자갈치 활어 횟집', ar: 'جاغالتشي هوتجيب', hi: 'जगलची फ्रेश होएतजिप' },
    area: { en: 'Jung-gu, Busan', ko: '부산 중구', ar: 'جونغ-غو، بوسان', hi: 'जुंग-गु, बुसान' },
    sigunguCode: '21010',
    coords: [129.0305, 35.0966],
    cuisine: 'seafood',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: false, vegetarianFriendly: false },
    confidence: 'phone',
    matchedTokens: ['횟집', '활어', '회'],
    repMenu: ['모둠회', '고등어회', '매운탕'],
    phoneVerifiedOn: '2026-06-11',
  },
  {
    id: 'r-busan-jung-milmyeon',
    name: { en: 'Nampo Milmyeon', ko: '남포동 밀면집' },
    area: { en: 'Jung-gu, Busan', ko: '부산 중구' },
    sigunguCode: '21010',
    coords: [129.0281, 35.0979],
    cuisine: 'korean',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: false },
    confidence: 'menu',
    matchedTokens: ['밀면'],
    repMenu: ['물밀면', '비빔밀면'],
  },
  {
    id: 'r-busan-yeongdo-hoetjip',
    name: { en: 'Yeongdo Coastal Hoetjip', ko: '영도 바닷가 횟집', ar: 'يونغدو الساحلي هوتجيب', hi: 'योंगदो तटीय होएतजिप' },
    area: { en: 'Yeongdo-gu, Busan', ko: '부산 영도구', ar: 'يونغدو، بوسان', hi: 'योंगदो-गु, बुसान' },
    sigunguCode: '21040',
    coords: [129.0678, 35.0912],
    cuisine: 'seafood',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: false, vegetarianFriendly: false },
    confidence: 'phone',
    matchedTokens: ['횟집', '물회', '회'],
    repMenu: ['자연산 물회', '멍게비빔밥', '해물탕'],
    phoneVerifiedOn: '2026-05-27',
  },
  {
    id: 'r-busan-yeongdo-samgyetang',
    name: { en: 'Yeongdo Samgyetang', ko: '영도 삼계탕' },
    area: { en: 'Yeongdo-gu, Busan', ko: '부산 영도구' },
    sigunguCode: '21040',
    coords: [129.0715, 35.0878],
    cuisine: 'korean-chicken',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: false },
    confidence: 'menu',
    matchedTokens: ['삼계탕'],
    repMenu: ['삼계탕', '들깨삼계탕'],
  },
  {
    id: 'r-busan-yeongdo-kebab',
    name: { en: 'Taejongdae Doner House', ko: '태종대 도너 하우스', ar: 'بيت الدونر تايجونغدايه', hi: 'ताएजोंगदे डोनर हाउस' },
    area: { en: 'Yeongdo-gu, Busan', ko: '부산 영도구' },
    sigunguCode: '21040',
    coords: [129.0836, 35.0538],
    cuisine: 'middle-eastern',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: true, vegetarianFriendly: true },
    confidence: 'name',
    matchedTokens: ['케밥', '도너', 'HALAL'],
    repMenu: ['도너 케밥', '후무스'],
  },
  {
    id: 'r-incheon-jung-hoetjip',
    name: { en: 'Yeonan Pier Hoetjip', ko: '연안부두 횟집' },
    area: { en: 'Jung-gu, Incheon', ko: '인천 중구' },
    sigunguCode: '23010',
    coords: [126.5983, 37.4491],
    cuisine: 'seafood',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: false, vegetarianFriendly: false },
    confidence: 'menu',
    matchedTokens: ['횟집', '회'],
    repMenu: ['광어회', '우럭매운탕'],
  },
  {
    id: 'r-incheon-jung-halal',
    name: { en: 'Chinatown Halal Grill', ko: '차이나타운 할랄 그릴', ar: 'مشواة حلال الحي الصيني', hi: 'चाइनाटाउन हलाल ग्रिल' },
    area: { en: 'Jung-gu, Incheon', ko: '인천 중구', ar: 'جونغ-غو، إنتشون', hi: 'जुंग-गु, इंचियोन' },
    sigunguCode: '23010',
    coords: [126.6178, 37.4744],
    cuisine: 'halal',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: true, vegetarianFriendly: true },
    confidence: 'phone',
    matchedTokens: ['HALAL', '할랄', '케밥'],
    repMenu: ['치킨 케밥', '양갈비 구이', '병아리콩 카레'],
    phoneVerifiedOn: '2026-07-01',
  },
  {
    id: 'r-incheon-yeonsu-hanwoo',
    name: { en: 'Songdo Hanwoo Garden', ko: '송도 한우 가든' },
    area: { en: 'Yeonsu-gu, Incheon', ko: '인천 연수구' },
    sigunguCode: '23040',
    coords: [126.6412, 37.3894],
    cuisine: 'korean-beef',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: true, vegetarianFriendly: false },
    confidence: 'name',
    matchedTokens: ['한우'],
    repMenu: ['한우 채끝', '차돌된장'],
  },
  {
    id: 'r-incheon-yeonsu-veg',
    name: { en: 'Songdo Vegan Bapsang', ko: '송도 비건 밥상' },
    area: { en: 'Yeonsu-gu, Incheon', ko: '인천 연수구' },
    sigunguCode: '23040',
    coords: [126.6489, 37.3835],
    cuisine: 'korean',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: true },
    confidence: 'menu',
    matchedTokens: ['채식', '비건'],
    repMenu: ['모둠 나물밥', '콩국수'],
  },
  {
    id: 'r-jeju-hoetjip',
    name: { en: 'Jeju Mulhoe Hoetjip', ko: '제주 물회 횟집', ar: 'جيجو مولهوه هوتجيب', hi: 'जेजू मुलहोए होएतजिप' },
    area: { en: 'Jeju-si, Jeju', ko: '제주 제주시', ar: 'جيجو-سي', hi: 'जेजू-सी' },
    sigunguCode: '39010',
    coords: [126.5312, 33.5113],
    cuisine: 'seafood',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: false, vegetarianFriendly: false },
    confidence: 'phone',
    matchedTokens: ['횟집', '물회', '자리'],
    repMenu: ['자리물회', '한치물회', '갈치조림'],
    phoneVerifiedOn: '2026-03-30',
  },
  {
    id: 'r-jeju-samgyetang',
    name: { en: 'Jeju Yeondon Samgyetang', ko: '제주 연돈 삼계탕' },
    area: { en: 'Jeju-si, Jeju', ko: '제주 제주시' },
    sigunguCode: '39010',
    coords: [126.5219, 33.4996],
    cuisine: 'korean-chicken',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: false },
    confidence: 'menu',
    matchedTokens: ['삼계탕'],
    repMenu: ['삼계탕', '녹두백숙'],
  },
  {
    id: 'r-seogwipo-temple',
    name: { en: 'Seogwipo Sanche Table', ko: '서귀포 산채정식' },
    area: { en: 'Seogwipo-si, Jeju', ko: '제주 서귀포시' },
    sigunguCode: '39020',
    coords: [126.5657, 33.2541],
    cuisine: 'temple',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: true },
    confidence: 'name',
    matchedTokens: ['사찰음식', '산채'],
    repMenu: ['산채정식', '표고버섯탕수'],
  },
  {
    id: 'r-eumseong-hanwoo',
    name: { en: 'Eumseong Hanwoo Maeul', ko: '음성 한우마을' },
    area: { en: 'Eumseong-gun, Chungbuk', ko: '충북 음성군' },
    sigunguCode: '33370',
    coords: [127.6906, 36.9403],
    cuisine: 'korean-beef',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: true, vegetarianFriendly: false },
    confidence: 'menu',
    matchedTokens: ['한우', '생고기'],
    repMenu: ['한우 모둠구이', '한우국밥'],
  },
  {
    id: 'r-eumseong-baeksuk',
    name: { en: 'Eumseong Valley Baeksuk', ko: '음성 계곡 백숙' },
    area: { en: 'Eumseong-gun, Chungbuk', ko: '충북 음성군' },
    sigunguCode: '33370',
    coords: [127.7241, 36.9587],
    cuisine: 'korean-chicken',
    attributes: { containsPork: false, servesAlcohol: false, containsBeef: false, vegetarianFriendly: false },
    confidence: 'name',
    matchedTokens: ['백숙', '삼계탕'],
    repMenu: ['토종닭 백숙', '누룽지 삼계탕'],
  },
  {
    id: 'r-ganghwa-hoetjip',
    name: { en: 'Ganghwa Tidal Flat Hoetjip', ko: '강화 갯벌 횟집' },
    area: { en: 'Ganghwa-gun, Incheon', ko: '인천 강화군' },
    sigunguCode: '23310',
    coords: [126.4848, 37.7469],
    cuisine: 'seafood',
    attributes: { containsPork: false, servesAlcohol: 'unknown', containsBeef: false, vegetarianFriendly: false },
    confidence: 'name',
    matchedTokens: ['횟집', '밴댕이'],
    repMenu: ['밴댕이회무침', '꽃게탕'],
  },
  {
    id: 'r-namhae-hoetjip',
    name: { en: 'Namhae Garlic Coast Hoetjip', ko: '남해 마늘해안 횟집' },
    area: { en: 'Namhae-gun, Gyeongnam', ko: '경남 남해군' },
    sigunguCode: '38350',
    coords: [127.8925, 34.8376],
    cuisine: 'seafood',
    attributes: { containsPork: false, servesAlcohol: true, containsBeef: false, vegetarianFriendly: false },
    confidence: 'phone',
    matchedTokens: ['횟집', '멸치', '회'],
    repMenu: ['멸치회무침', '갈치회', '해물뚝배기'],
    phoneVerifiedOn: '2026-06-25',
  },
];

export function getRestaurants(filter: RestaurantFilter = {}): Restaurant[] {
  return applyRestaurantFilter(RESTAURANTS, filter);
}

export function getRestaurant(id: string): Restaurant | undefined {
  return RESTAURANTS.find((r) => r.id === id);
}

export function getRegions(): RegionGap[] {
  return regionGapJson as RegionGap[];
}

export function getRegion(code: string): RegionGapDetail | undefined {
  const base = getRegions().find((r) => r.code === code);
  if (!base) return undefined;
  const topCandidateIds = RESTAURANTS.filter((r) => r.sigunguCode === code).slice(0, 3).map((r) => r.id);
  return { ...base, topCandidateIds, processingStatus: 'menu-checked' };
}

export function getComparisonRegions(): [RegionGap, RegionGap, RegionGap] {
  const byCode = (c: string) => getRegions().find((r) => r.code === c)!;
  return [byCode('11030'), byCode('21040'), byCode('33370')];
}
